[package]
name = "glowy"
description = "Information flow control analysis for Go"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[workspace]
members = [".", "parser"]

[workspace.dependencies]
codespan-reporting = "0.11.1"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Rafael Oliveira", "Diogo Correia"]
repository = "https://github.com/RafDevX/glowy"
license = "MIT"
rust-version = "1.82"

[dependencies]
codespan-reporting.workspace = true
parser = { path = "parser" }
