[package]
name = "glowy-cli"
description = "Information flow control analysis for Go"
documentation = "https://glowy.rso.pt/glowy"
readme = "./README-crates-io.md"
include = ["/src/**"]
keywords = ["security", "cli", "tool", "go", "static-analysis"]
categories = ["security", "development-tools", "command-line-utilities"]
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[workspace]
members = [".", "lib", "parser"]

[workspace.dependencies]
codespan-reporting = "0.13.1"
regex = "1.13.0"

[workspace.package]
version = "1.0.0"
edition = "2024"
authors = ["Rafael Oliveira", "Diogo Correia"]
repository = "https://github.com/RafDevX/glowy"
license = "MIT"
rust-version = "1.91"

# make the binary leaner and more optimized
# (at the cost of a slower compile time, though only for release mode)
# this applies for all packages in this workspace
[profile.release]
lto = true        # fat link-time optimizations across all crates
strip = true      # full symbol stripping from generated binary
codegen-units = 1 # no parallelism processing a crate, max optimization
panic = "abort"   # smaller binary since no unwinding mechanism

[profile.flamegraph]
inherits = "release"
debug = true         # allow resolving to file:line
lto = "thin"         # less aggressive cross-crate inlining
strip = "none"       # do not strip symbols
codegen-units = 16   # less inlining so we get more named frames

[dependencies]
annotate-snippets = "0.12.10"
anstream = "1.0.0"
clap = { version = "4.5.51", features = ["derive"] }
colored = "3.1.1"
glowy = { version = "1.0.0", path = "./lib" }
