[package]
name = "glowy"
description = "Information flow control analysis for Go"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[workspace]
members = [".", "parser"]

[workspace.dependencies]
codespan-reporting = "0.11.1"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Rafael Oliveira", "Diogo Correia"]
repository = "https://github.com/RafDevX/glowy"
license = "MIT"
rust-version = "1.86"

[dependencies]
annotate-snippets = "0.12.10"
anstream = "0.6.21"
clap = { version = "4.5.51", features = ["derive"] }
colored = "3.1.1"
parser = { path = "parser" }
rayon = "1.11.0"
uuid = { version = "1.19.0", features = ["v4"] }
