{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";
    unstable.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs =
    {
      nixpkgs,
      unstable,
      flake-utils,
      ...
    }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs { inherit system; };
        unstablePkgs = import unstable { inherit system; };
      in
      {
        packages = rec {
          glowy-cli = pkgs.callPackage ./package.nix { };
          default = glowy-cli;
        };

        devShells.default = pkgs.mkShellNoCC {
          buildInputs =
            (with pkgs; [
              gcc # rust needs cc linker
            ])
            ++ (with unstablePkgs; [
              rustc
              cargo
              rustfmt

              rust-analyzer
              clippy
              cargo-make
              cargo-flamegraph
            ]);

          shellHook = ''
            export RUST_SRC_PATH="${unstablePkgs.rust.packages.stable.rustPlatform.rustLibSrc}"

            mkdir -p .vscode
            cat > .vscode/settings.json <<EOF
            // Auto-generated by flake.nix
            {
              "rust-analyzer.cargo.sysrootSrc": "$RUST_SRC_PATH",
              "rust-analyzer.check.command": "clippy",
              "cSpell.words": [
                "anstream",
                "codespan",
                "clippy",
                "deque",
                "direnv",
                "finl",
                "flamegraph",
                "funcs",
                "getenv",
                "glowy",
                "goarch",
                "hexdigit",
                "ilog",
                "imag",
                "impls",
                "indexmap",
                "nixos",
                "nixpkgs",
                "pathbuf",
                "peekable",
                "pkgs",
                "predeclared",
                "println",
                "referer",
                "reqs",
                "rfind",
                "rsplit",
                "rustc",
                "scrutinee",
                "serde",
                "subenum",
                "subspan",
                "symtab",
                "syscall",
                "unioned",
                "unseparated",
                "worklist",
                "worklists"
              ]
            }
            EOF
          '';
        };
      }
    );
}
