# run with `cargo make <task>`

[tasks.fmt-unstable]
workspace = false
command = "cargo"
args = [
    "fmt",
    "--",
    "--config",
    "use_field_init_shorthand=true,unstable_features=true,format_code_in_doc_comments=true,format_generated_files=false,format_strings=true,group_imports=StdExternalCrate,imports_granularity=Crate,normalize_comments=true,reorder_impl_items=true,wrap_comments=true",
    # pass additional args, e.g. `cargo make fmt-unstable --check`
    "${@}",
]

[tasks.ifc-benchmarks]
workspace = false
command = "cargo"
args = ["run", "--", "--summary-only", "--multi-suites", "./ifc-benchmarks"]

[tasks.flamegraph]
workspace = false
env = { RUSTFLAGS = "-C force-frame-pointers=yes -C force-unwind-tables=yes" }
command = "cargo"
args = [
    "flamegraph",
    "--profile",
    "flamegraph",
    "--bin",
    "glowy-cli",
    # "--freq", # can't actually do it because already in custom command below
    # Hz, 99 is good for long (>5 min) runs
    # (should be a prime number to sidestep regular events/timers)
    # "99",
    # we need to use a custom command because hardware-level event `cycles:u`
    # does not work properly on all machines, so parallel tasks can show up as
    # [unknown]; using software-level `task-clock:u` works (`:u` = user-space)
    "--cmd",
    "record -F 99 -g -e task-clock:u",
    "--",
    # pass additional args, e.g. `cargo make flamegraph /path/to/some/proj`
    "${@}",
]
