{
  pkgs ? (import <nixpkgs> { }),
  unstable ? (import <unstable> { }),
}:
pkgs.mkShellNoCC {
  buildInputs =
    (with pkgs; [
      gcc # need cc linker
    ])
    ++ (with unstable; [
      rustc
      cargo
      rustfmt

      rust-analyzer
      clippy
      cargo-make
    ]);

  shellHook = ''
    export RUST_SRC_PATH="${unstable.rust.packages.stable.rustPlatform.rustLibSrc}"

    mkdir -p .vscode
    cat > .vscode/settings.json <<EOF
    // Auto-generated by shell.nix
    {
      "rust-analyzer.cargo.sysrootSrc": "$RUST_SRC_PATH",
      "rust-analyzer.check.command": "clippy",
      "cSpell.words": [
        "anstream",
        "codespan",
        "clippy",
        "deque",
        "direnv",
        "finl",
        "funcs",
        "glowy",
        "hexdigit",
        "imag",
        "impls",
        "nixpkgs",
        "pathbuf",
        "peekable",
        "pkgs",
        "predeclared",
        "println",
        "rsplit",
        "rustc",
        "scrutinee",
        "subenum",
        "symtab",
        "unseparated"
      ]
    }
    EOF
  '';
}
