{
  pkgs ? (import <nixpkgs> { }),
}:
pkgs.mkShellNoCC {
  buildInputs = with pkgs; [
    rustc
    cargo
    rustfmt
    gcc # need cc linker

    rust-analyzer
    clippy
    cargo-make
  ];

  shellHook = ''
    export RUST_SRC_PATH="${pkgs.rust.packages.stable.rustPlatform.rustLibSrc}"

    mkdir -p .vscode
    cat > .vscode/settings.json <<EOF
    // Auto-generated by shell.nix
    {
      "rust-analyzer.cargo.sysrootSrc": "$RUST_SRC_PATH",
      "rust-analyzer.check.command": "clippy",
      "cSpell.words": [
        "anstream",
        "codespan",
        "clippy",
        "deque",
        "direnv",
        "finl",
        "funcs",
        "glowy",
        "hexdigit",
        "imag",
        "impls",
        "nixpkgs",
        "pathbuf",
        "peekable",
        "pkgs",
        "predeclared",
        "println",
        "rsplit",
        "rustc",
        "scrutinee",
        "symtab",
        "unseparated"
      ]
    }
    EOF
  '';
}
